auth_system/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from sqlalchemy.orm import sessionmaker, scoped_session

from app import manager, app
# from flask_security import SQLAlchemyUserDatastore, Security
from flask_login import current_user, login_user, logout_user, login_required, login_required

from db_connection import engine
from models import User
from werkzeug.security import generate_password_hash, check_password_hash

auth_system = Blueprint("auth_system", __name__, template_folder="templates")
session_factory = sessionmaker(bind=engine)
Session = scoped_session(session_factory=session_factory)


@manager.user_loader
def load_user(user_id):
    # return User.query.get(user_id)
    return Session.get(User, user_id)


@auth_system.route("/test", methods=["GET"])
def test():
    return "<h1> OK! </h1>"


@auth_system.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":

        login = request.form.get("login")
        password = request.form.get("password")
        user = Session.query(User).filter_by(email=login).first()
        if user:
            if not login or not password:
                flash("Попробуйте ещё раз!")
            else:
                if user.check_password(password):
                    login_user(user)
                    return redirect(url_for('auth_system.test'))
    return render_template("auth_system/loginPage.html")


@auth_system.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("auth_system.login"))


@auth_system.route("/register", methods=["POST", "GET"])
def register():
    if request.method == "POST":
        # name = request.form.get("name")
        # surname = request.form.get("surname")
        password = request.form.get("password")
        email = request.form.get("email")
        if not password or not email:
            flash("Некорректно введённые данные! Пробуйте ещё раз!")
        else:
            user = User(
                email=email,
                active=True,
                password=str(password),
            )

            Session.add(user)
            Session.commit()
            return redirect(url_for("auth_system.login"))
    return render_template("auth_system/registerPage.html")

auth_system/templates/auth_system/loginPage.html
{% extends 'base.html' %}

{% block content %}
<div class="offset-md-3 col-md-6">

<form method="POST">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" >Email address</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="login">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Войти</button>
<a href="{{url_for('auth_system.register')}}" class="btn btn-danger">Регистрация </a>
</form>
</div>
{% endblock %}
<!--<form method="POST">-->
<!--    <td> Введите Ваш логин </td>-->
<!--    <td> <input type="text" name="login"> </td>-->
<!--    <p> </p>-->
<!--    <td> Введите Ваш пароль </td>-->
<!--    <td> <input type="password"  name="password"> </td>-->
<!--    <p> </p>-->

<!--&lt;!&ndash;    <td> Введите Ваш логин </td>&ndash;&gt;-->
<!--    <td> <input type="submit"> </td>-->
<!--</form>-->


<!--</body>-->
<!--</html>-->

auth_system/templates/auth_system/registerPage.html
{% extends 'base.html' %}

{% block content %}
<div class="offset-md-3 col-md-6">

<form method="POST">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" >Введите вашу почту</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
    <div id="emailHelp" class="form-text">Ваши личные данные защищены шифрованием</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" >Введите ваше имя</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">
    <div id="emailHelp" class="form-text">Ваши личные данные защищены шифрованием</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" >Введите вашу фамилию</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="surname">
    <div id="emailHelp" class="form-text">Ваши личные данные защищены шифрованием</div>
  </div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Придумайте пароль</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>

  <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
  <a href="{{url_for('auth_system.login')}}" class="btn btn-danger">Войти </a>

</form>
</div>
{% endblock %}
<!--<form method="POST">-->
<!--    <td> Введите Ваш логин </td>-->
<!--    <td> <input type="text" name="login"> </td>-->
<!--    <p> </p>-->
<!--    <td> Введите Ваш пароль </td>-->
<!--    <td> <input type="password"  name="password"> </td>-->
<!--    <p> </p>-->

<!--&lt;!&ndash;    <td> Введите Ваш логин </td>&ndash;&gt;-->
<!--    <td> <input type="submit"> </td>-->
<!--</form>-->


<!--</body>-->
<!--</html>-->

auth_system/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <meta charset="UTF-8">
    {% block title %}

    {% endblock title %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('index')}}"><b>TechEdu</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if current_user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link active" href="#">Выбрать время</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" href="#">Общий репозиторий</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('courses.index')}}">Список курсов</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('courses.my_courses')}}">Мои курсы</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" href="{{url_for('auth_system.logout')}}">Выйти</a>
        </li>
      </ul>
     <form class="d-flex" method="get" action="{{url_for('search.index')}}">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" value="{{request.args.get('search', '')}}">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        {%endif%}
    </div>
  </div>
</nav>
{% block content_title%}
{% endblock content_title %}
{% block content %}
{% endblock content %}

{% block comment %}

{% endblock comment %}


</body>
</html>

auth_system/templates/status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<h1>Hello!!!</h1>

</body>
</html>